In [124]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [125]:
df=pd.read_csv("iris.csv",header=None)

In [126]:
df.tail()

0    1    2    3               4
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [127]:
X=df.values

In [128]:
X[np.where((X[:,4] =='Iris-setosa') ),4]=0
X[np.where((X[:,4] =='Iris-versicolor')),4 ]=1
X[np.where((X[:,4] =='Iris-virginica') ),4]=2


## converting data into X AND Y


In [129]:
x=X[:,:4]
y=X[:,4]

In [130]:
x_setosa=x[:50,:]
y_setosa=y[:50]
x_versicolor=x[50:100,:]
y_versicolor=y[50:100]
x_virginica=x[100:,:]
y_virginica=y[100:]

In [131]:
X_setosa.shape , X_versicolor.shape , X_virginica.shape

((50, 5), (50, 5), (50, 5))

## Converting data into train ,validate and test set

In [132]:
x_train_setosa=x_setosa[:30,:]
y_train_setosa=y_setosa[:30]
x_valid_setosa=x_setosa[30:40,:]
y_valid_setosa=y_setosa[30:40]
x_test_setosa=x_setosa[40:50,:]
y_test_setosa=y_setosa[40:50]


In [133]:
x_train_versicolor=x_versicolor[:30,:]
y_train_versicolor=y_versicolor[:30]
x_valid_versicolor=x_versicolor[30:40,:]
y_valid_versicolor=y_versicolor[30:40]
x_test_versicolor=x_versicolor[40:50,:]
y_test_versicolor=y_versicolor[40:50]

In [134]:
x_train_virginica=x_virginica[:30,:]
y_train_virginica=y_virginica[:30]
x_valid_virginica=x_virginica[30:40,:]
y_valid_virginica=y_virginica[30:40]
x_test_virginica=x_virginica[40:50,:]
y_test_virginica=y_virginica[40:50]

In [135]:
x_train=np.concatenate((x_train_setosa,x_train_versicolor,x_train_virginica),axis=0)
x_valid=np.concatenate((x_valid_setosa,x_valid_versicolor,x_valid_virginica),axis=0)
x_test=np.concatenate((x_test_setosa,x_test_versicolor,x_test_virginica),axis=0)

In [136]:
y_train=np.concatenate((y_train_setosa,y_train_versicolor,y_train_virginica),axis=0)
y_valid=np.concatenate((y_valid_setosa,y_valid_versicolor,y_valid_virginica),axis=0)
y_test=np.concatenate((y_test_setosa,y_test_versicolor,y_test_virginica),axis=0)

In [137]:
def distance(x1,x2):
    return np.sqrt(np.sum((x1-x2)**2))

def accuracy(y_pred,y):
    m=y_pred.shape[0]
    return np.sum(y_pred==y)/m
def knn(X,Y,XX,k):
    m=X.shape[0]
    n=XX.shape[0]
    labels=[]
    for j in range(n):
        l=[]
        for i in range(m):
            dist=distance(XX[j],X[i])
            l.append((dist,Y[i]))
        val=sorted(l)
        val=val[:k]
        val=np.array(val)
        r=np.unique(val[:,1],return_counts=True)
        idx=np.argmax(r[1])
        labels.append(r[0][idx])
    return labels    


## getting perfect k

In [145]:
acc=-1
K=0
for k in range(1,6):
    labels=knn(x_train,y_train,x_valid,k)
    labels=np.array(labels)
    ac=accuracy(labels,y_valid)
    print(ac)
    if ac > acc:
        acc=ac
        K=k
        

0.9333333333333333
0.9
0.9666666666666667
0.9666666666666667
0.9666666666666667


### testing

In [146]:
labels=knn(x_train,y_train,x_test,K)
labels=np.array(labels)
ac=accuracy(labels,y_test)

In [147]:
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [143]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=object)

In [148]:
from sklearn.neighbors import KNeighborsClassifier

In [149]:
neigh = KNeighborsClassifier(n_neighbors=3)

In [155]:
neigh.fit(x_train, list(y_train))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [153]:
x_train.shape, y_train.shape

((90, 4), (90,))

In [157]:
neigh.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [158]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=object)